# -*- coding: utf-8 -*-
"""Eleicoes 2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T7njxngrjoJKD1cdM5BF2Bv5g3jX01G-
"""

#!pip install requests

#!pip install json

#!pip install pandas

"""###Importando bibliotecas"""

import requests
import json
import pandas as pd
import time
import matplotlib.pyplot as plt

"""####Informe qual turno vai realizar a consulta"""

turno = 2

#API para consulta dos dados

if turno == 1:
    url = 'http://resultados.tse.jus.br/oficial/ele2022/544/dados-simplificados/br/br-c0001-e000544-r.json'
else:
    url = 'http://resultados.tse.jus.br/oficial/ele2022/545/dados-simplificados/br/br-c0001-e000545-r.json'

"""####Extração, carregamento e tratamentos dos dados. Geração do grafico."""

def apuracao():
    data = requests.get(url)
    json_data = json.loads(data.content)
    candidato = []
    partido = []
    votos = []
    porcentagem = []
    for informacoes in json_data['cand']:
        candidato.append(informacoes['nm'])
        votos.append(informacoes['vap'])
        porcentagem.append(informacoes['pvap'])
    df_eleicao = pd.DataFrame(list(zip(candidato, votos, porcentagem)),
                              columns=['Candidato', 'Nº Votos', 'Porcentagem'])
    df_eleicao['Nº Votos'] = df_eleicao['Nº Votos'].astype(int)
    df_eleicao['Porcentagem'] = df_eleicao['Porcentagem'].str.replace(',', '.', regex=True)
    df_eleicao['Porcentagem'] = df_eleicao['Porcentagem'].astype(float)
    # df_eleicao.info()
    df1 = df_eleicao['Nº Votos'].iloc[2:11].sum()
    # df1
    df2 = df_eleicao['Porcentagem'].iloc[2:11].sum()
    # df2
    columns = ['Candidato', 'Nº Votos', 'Porcentagem']
    # columns
    if turno == 1:
      z = ['OUTROS', df1, df2]
      # z
      dict_from_list = dict(zip(columns, z))
      # print(dict_from_list)
      df_eleicao2 = pd.DataFrame([dict_from_list])
      # df_eleicao2
    df_eleicao = df_eleicao.iloc[0:2]
    if turno == 1:
      df_eleicao = pd.merge(df_eleicao, df_eleicao2, how='outer')
    return df_eleicao

def apurar():
    df_eleicao = apuracao()
    df_eleicao
    df_candidato = df_eleicao['Candidato'].tolist()
    df_votos = df_eleicao['Nº Votos'].tolist()
    df_percentual = df_eleicao['Porcentagem'].tolist()
    
    if (df_eleicao['Nº Votos'].sum() == 0):
      print(df_eleicao)
      print('Apuração ainda nao iniciada!')
    else:
      print(df_eleicao)
      # Gráfico de Pizza
      fig = plt.figure(figsize=(10, 7))
      plt.pie(df_votos, labels=df_candidato, autopct='%1.2f%%')
      plt.show()
      #st.pyplot(plt)
      plt.clf()

      # Gráfico de Barras
      plt.bar(df_candidato, df_percentual)
      plt.xlabel("Candidatos")
      plt.ylabel("% Votos")
      plt.title("Eleições 2º Turno - 2022")
      #plt.show()
      #st.pyplot(plt)
      plt.clf()

#Executando a função
apurar()

